name: Update Database

on:
  push:
    branches:
      - main

jobs:
  update_database:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run SQL script
      shell: cmd
      run: |
        cmd /c "C:\OSPanel\modules\database\MySQL-5.7-Win10\bin\mysql.exe" -h localhost -u root < update_database.sql
